### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mhdomo** [cainus/logdriver#4]
Hello there,

Could you please add a license?

**Comment by cainus** [comment]
fixed!

**Comment by mhdomo** [comment]
Cheers!

**Comment by Walther** [comment]
Apparently, this addition has not been released to npm yet.

If you run `yarn add log-driver` and `cat node_modules/log-driver/package.json`, you'll see that the license field is missing. Additionally, at the log-driver [npm page](https://www.npmjs.com/package/log-driver) the license is not visible at the right bar.

I noticed this when using [tldrlegal](https://github.com/eladnava/tldrlegal) to check the licenses of my dependencies in a project, this was reported as not having a known license.

A simple publish / update to npm should solve this, as I see both the `LICENSE` file and the license field in `package.json` here in the repository.

**Comment by jinwoo** [comment]
I filed https://github.com/cainus/logdriver/issues/9 for publishing a new npm package. Please help us.
